# IMEC2001 Herramientas Computacionales 
## Actividad Clase 9: Sistemas de Ecuaciones
### Fecha Límite Entrega (Bloque Neón): <font color="#FF5733">23.59h de Septiembre 6, 2023</font>

Universidad de los Andes — Septiembre 4, 2023.

___
### Tener en Cuenta
La entrega de la **Actividad Clase 9** se puede realizar de dos maneras:
1. Enviar vía Bloque Neón el archivo en Jupyter Notebook (extensión '.ipynb').
2. Enviar vía Bloque Neón el archivo PDF del Jupyter Notebook.

**Nota:** <font color="#FF5733">El nombre del archivo debe ser: `AC9_NombreApellido.ipynb`.</font>

---

## TABLA DE CONTENIDO

### Sección 1: Ejercicios [→](#section1)
1. Ejercicio 1: Ecuaciones Lineales [→](#exercise1)
2. Ejercicio 2: Ecuaciones No Lineales [→](#exercise2)
___

<a id="section1"></a>
# Sección 1: Ejercicios

<a id="exercise1"></a>
## Ejercicio 1: Ecuaciones Lineales

Se tiene el siguiente sistema de ecuaciones lineales:

$$
\begin{cases}
  3x_1 + 2x_2 + x_3 = 1 \\ 
  \\
  2x_1 + 2x_2 + 4x_3 = -2 \\
  \\
  -x_1 + \frac{1}{2}x_2 - x_3 = 0
\end{cases} 
$$

<div class="alert alert-block alert-warning">

1. Utilizando la librería `numpy.linalg.inv` y `numpy.dots`, resuelva el sistema de ecuaciones.
2. Utilizando la librería `numpy.linalg.solve`, resuelva el sistema de ecuaciones.
3. Utilizando la librería `sympy.rref()`, resuelva el sistema de ecuaciones.
4. Utilizando la librería `scipy.optimize.fsolve`, resuelva el sistema de ecuaciones.
5. Utilizando la librería `sympy.solve`, resuelva el sistema de ecuaciones.
    
</div>

In [11]:
#Cargar librerías

# Datos y Gráficas
%matplotlib inline
import matplotlib.pyplot as plt
import pandas as pd

# Sistema de Ecuaciones
import numpy as np
from scipy import optimize
import sympy

In [9]:
# Ítem 1
a = np.array([[3,2,1], [2,2,4], [-1,1/2,1]])

b = np.array([1,-2,0])

inva = np.linalg.inv(a)

x = np.dot(inva, b)
x

array([-0.33333333,  1.55555556, -1.11111111])

In [10]:
# Ítem 2
a = np.array([[3,2,1], [2,2,4], [-1,1/2,1]])

b = np.array([1,-2,0])

x = np.linalg.solve(a,b)
x

array([-0.33333333,  1.55555556, -1.11111111])

In [13]:
# Ítem 3
a_aumentada = sympy.Matrix([[3,2,1,1], [2,2,4,-2], [-1,1/2,1,0]])

x = a_aumentada.rref()[0]
x

Matrix([
[1, 0, 0, -0.333333333333333],
[0, 1, 0,   1.55555555555556],
[0, 0, 1,  -1.11111111111111]])

In [23]:
# Ítem 4
# PASO 1. Definir la función
def f(a):
    ## Definimos las incógnitas
    x1 = a[0]
    x2 = a[1]
    x3 = a[2]
    
    ## Creamos una lista vacía para alojar las funciones
    F = np.zeros(3)
    
    ## Alojamos las funciones en F (noten la parte derecha igual a cero)
    F[0] = 3*x1 + 2*x2 + x3 + 1
    F[1] = 2*x1 + 2*x2 + 4*x3 - 2
    F[2] = -1*x1 + (1/2)*x2 - x3 + 0
    
    return F

estimacion  = [0.33 , 1.5 , -1.1]
x = optimize.fsolve(func = f, x0 = estimacion)
x


array([-0.69230769,  0.15384615,  0.76923077])

In [25]:
# Ítem 5
x1 = sympy.Symbol('x_1')
x2 = sympy.Symbol('x_2')
x3 = sympy.Symbol('x_3')

ec1 = sympy.Eq(3*x1 + 2*x2 + x3, 1) # La derecha de la igualdad va después de la coma
ec2 = sympy.Eq(2*x1 + 2*x2 + 4*x3,- 2)
ec3 = sympy.Eq(-1*x1 + (1/2)*x2 - x3, 0)

sol = sympy.solve([ec1, ec2, ec3], # Lista de ecuaciones
                  [x1, x2,x3]) # Lista de símbolos
sol

{x_1: 0.692307692307692, x_2: -0.153846153846154, x_3: -0.769230769230769}

<a id='exercise2'></a>
## Ejercicio 2: Ecuaciones No Lineales

Se tiene el siguiente sistema de ecuaciones no lineales:

$$
\begin{cases}
  x^2 + y^2 = 1 \\ 
  \\
  xy + yz = -1.1 \\
  \\
  y^2 + z^2 = 2
\end{cases} 
$$

<div class="alert alert-block alert-warning">

1. Utilizando la librería `scipy.optimize.fsolve`, resuelva el sistema de ecuaciones.
1. Utilizando la librería `scipy.optimize.roots`, resuelva el sistema de ecuaciones.
3. Utilizando la librería `sympy.solve`, resuelva el sistema de ecuaciones.
    
</div>

In [29]:
# Ítem 1
from scipy import optimize

# PASO 1. Definir la función
def f(a):
    ## Definimos las incógnitas
    x = a[0]
    y = a[1]
    z = a[2]
    ## Creamos una lista vacía para alojar las funciones
    F = np.zeros(3)
    
    ## Alojamos las funciones en F (noten la parte derecha igual a cero)
    F[0] = x**2 + y**2 - 1
    F[1] = x * y + y * x + 1.1
    F[2] = y**2 + z**2 - 2
    return F

estimacion = [1,1,1]

sol = optimize.fsolve(func=f,
                      x0=estimacion)
sol 

c:\Users\dazam\Anaconda\lib\site-packages\scipy\optimize\minpack.py:175: RuntimeWarning: The iteration is not making good progress, as measured by the 
  improvement from the last five Jacobian evaluations.
  warnings.warn(msg, RuntimeWarning)


array([-0.72463231,  0.72450741,  1.21453453])

In [36]:
# Ítem 2

# PASO 1. Definir la función
def f(a):
    ## Definimos las incógnitas
    x = a[0]
    y = a[1]
    z = a[2]
    
    ## Creamos una lista vacía para alojar las funciones
    F = np.array( [ x**2 + y**2 - 1,
                     x * y + y * z + 1.1, y**2 + z**2 - 2 ]) 
    return F

estimacion = [-0.8,0.5, -1.3]
x = optimize.root(fun=f,
                  x0=estimacion)

x

    fjac: array([[-0.96218169,  0.27240628, -0.00110501],
       [-0.23975595, -0.84491595,  0.478157  ],
       [-0.12931933, -0.46033884, -0.87827368]])
     fun: array([ 8.99236241e-12, -2.38808973e-12, -4.30322444e-12])
 message: 'The solution converged.'
    nfev: 10
     qtf: array([ 2.28687352e-10,  3.69080930e-10, -6.91311757e-11])
       r: array([ 1.78222233, -1.58776103,  0.17222906,  2.06490602, -1.63602758,
        2.08018492])
  status: 1
 success: True
       x: array([-0.86413935,  0.5032526 , -1.32164172])

In [35]:
# Ítem 3
x = sympy.Symbol('x')
y = sympy.Symbol('y')
z = sympy.Symbol('z')

ec1 = sympy.Eq( x**2 + y**2 - 1)
ec2 = sympy.Eq(x * y + y * z + 1.1)
ec3 = sympy.Eq( y**2 + z**2 - 2)

sol = sympy.solve([ec1, ec2, ec3], # Lista de ecuaciones
                  [x,y,z]) # Lista de símbolos
sol


c:\Users\dazam\Anaconda\lib\site-packages\sympy\core\relational.py:495: SymPyDeprecationWarning: 

Eq(expr) with rhs default to 0 has been deprecated since SymPy 1.5.
Use Eq(expr, 0) instead. See
https://github.com/sympy/sympy/issues/16587 for more info.

  SymPyDeprecationWarning(


[(-0.864139354188464, 0.503252597154495, -1.32164171523800),
 (-0.100560885095735, 0.994930906339110, -1.00504352722220),
 (0.100560885095735, -0.994930906339110, 1.00504352722220),
 (0.864139354188464, -0.503252597154495, 1.32164171523800)]